[project]
name = "kanban-gui"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
"dnspython>=2.8.0",
"iniconfig>=2.3.0",
"packaging>=25.0",
"pymongo>=4.14.1",
"pytest>=9.0.1",
"ttkbootstrap>=1.14.2",
]

[tool.uv]